"""Versioned RealityCI domain schemas."""

from __future__ import annotations

from .base import ProducerInfo, RealityCIRecord, verify_seal
from .campaign import Campaign, CampaignConfig, CampaignObjective, CampaignWorld
from .capability import (
    CapabilityDebtContribution,
    CapabilityRecord,
    CapabilityState,
    CaptureMission,
    DebtFormula,
    RealityDebtSnapshot,
)
from .core import ArtifactKind, ArtifactRef, DomainEvent, EventType
from .diagnosis import (
    CausalDiagnosis,
    CausalHypothesis,
    CounterfactualExperiment,
    DiagnosisStatus,
    EstablishedPattern,
    ExperimentOutcome,
    ExperimentStatus,
    HypothesisKind,
    HypothesisStatus,
    InterventionName,
)
from .run import (
    FailureClass,
    FailureRecord,
    FailureSeverity,
    PolicyAdapterKind,
    PolicyDescriptor,
    RunEvidence,
    RunEvidenceBody,
    RunMetrics,
    RunResult,
)
from .scenario import (
    AppearanceSpec,
    DerivationInfo,
    EgoSpec,
    OccluderSpec,
    PedestrianSpec,
    RouteSpec,
    ScenarioManifest,
    ScenarioProvenance,
    WorldRef,
)
from .training import (
    CheckpointArtifact,
    Curriculum,
    CurriculumDimension,
    CurriculumStage,
    DatasetManifest,
    DatasetSplitCounts,
    TrainingJob,
    TrainingJobStatus,
    TrainingLimits,
    TrainingMetricsPoint,
)
from .verification import (
    ArmResult,
    Decision,
    ExamStatus,
    GateCheck,
    HiddenExam,
    ProtectedSuite,
    PromotionDecision,
    RegressionReport,
    ScenarioOutcomeCounts,
    SuiteComparison,
    WilsonInterval,
)

__all__ = [
    "ProducerInfo",
    "RealityCIRecord",
    "verify_seal",
    "Campaign",
    "CampaignConfig",
    "CampaignObjective",
    "CampaignWorld",
    "CapabilityDebtContribution",
    "CapabilityRecord",
    "CapabilityState",
    "CaptureMission",
    "DebtFormula",
    "RealityDebtSnapshot",
    "ArtifactKind",
    "ArtifactRef",
    "DomainEvent",
    "EventType",
    "CausalDiagnosis",
    "CausalHypothesis",
    "CounterfactualExperiment",
    "DiagnosisStatus",
    "EstablishedPattern",
    "ExperimentOutcome",
    "ExperimentStatus",
    "HypothesisKind",
    "HypothesisStatus",
    "InterventionName",
    "FailureClass",
    "FailureRecord",
    "FailureSeverity",
    "PolicyAdapterKind",
    "PolicyDescriptor",
    "RunEvidence",
    "RunEvidenceBody",
    "RunMetrics",
    "RunResult",
    "AppearanceSpec",
    "DerivationInfo",
    "EgoSpec",
    "OccluderSpec",
    "PedestrianSpec",
    "RouteSpec",
    "ScenarioManifest",
    "ScenarioProvenance",
    "WorldRef",
    "CheckpointArtifact",
    "Curriculum",
    "CurriculumDimension",
    "CurriculumStage",
    "DatasetManifest",
    "DatasetSplitCounts",
    "TrainingJob",
    "TrainingJobStatus",
    "TrainingLimits",
    "TrainingMetricsPoint",
    "ArmResult",
    "Decision",
    "ExamStatus",
    "GateCheck",
    "HiddenExam",
    "ProtectedSuite",
    "PromotionDecision",
    "RegressionReport",
    "ScenarioOutcomeCounts",
    "SuiteComparison",
    "WilsonInterval",
]
